### PR TITLE
Add libyaml to ncrc make template files

### PR DESCRIPTION
**Pull request by ceblanton**
Needed for the transition from *_table ascii input files to *_yaml files

### CODE REVIEW

**Comment by underwoo** [comment]
The ncrc system has the pkgconfig files available for lilbyaml `yaml-0.1`.  The information can be collected via the commands:

```
pkg-config --libs yaml-0.1
pkg-config --cflags yaml-0.1
```

I think it would be better to use pkg-config.

Another option would be to have ORNL add the correct _bits_ to the libyaml files to have the `ftn` and `cc` wrappers do this for us automatically.

**Comment by ceblanton** [comment]
Fixed. Thanks @underwoo, that's much better, I agree. I also tested the Intel one on gaea which worked.

**Comment by ceblanton** [comment]
If you can, please quash these 4 commits into one during merging (the first 3 commits don't have much use in the git history). The message in the last commit is the most informative. Thanks!

**Comment by uramirez8707** [comment]
@ceblanton @underwoo Can this be merged and added to fre/test soon? 
FMS main is now using libyaml and this will be helpful when testing.

**Comment by ceblanton** [comment]
@underwoo OK to merge? We also should create a tag before using it in fre/test.

**Review by underwoo — APPROVED** [review]

**Pull request merged**
